# safelist
branches:
  only:
    - /.*/

matrix:
  fast_finish: true
  include:

    -   language: node_js
        node_js: 10
        script: npm install && npm run build:prod && npm run test:ci
        os: linux
        dist: xenial
