name: CI Check

on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '10'
      - name: npm install
        run: npm install
      - name: Build production
        run: npm install && npm run build:prod
      - name: Test
        run: npm run test:ci


